basePath: /
definitions:
  common.CommonResHead:
    properties:
      code:
        type: integer
      content:
        type: object
      desc:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger go-svr-template API
  version: "1.0"
paths:
  /test/ping:
    get:
      consumes:
      - application/json
      description: http://127.0.0.1:8010/test/ping?content=1111
      parameters:
      - description: ping pong content
        in: path
        name: content
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.CommonResHead'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.CommonResHead'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.CommonResHead'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.CommonResHead'
      summary: Test Sever is working
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
